name: green
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  lottie: ^2.7.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.1
  http: ^1.0.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/air.json
    - assets/suhu.json
    - assets/daun.json
